var map = {
  models: {
    missile: [
      'x',
      'x',
      '8',
    ],
    squid: [
      '-------------',
      '----xxxxx----',
      '---xxxxxxx---',
      '---xx8x8xx---',
      '--xxxxxxxxx--',
      '----x-x-x----',
      '---x--x--x---',
      '--x---x---x--',
      '-------------',
    ],
    crab: [
      '-------------',
      '-----x-x-----',
      '----xx-xx----',
      '---xx0x0xx---',
      '---xxoxoxx---',
      '--xxxxxxxxx--',
      '---x-x-x-x---',
      '--x--x-x--x--',
      '-------------',
    ],
    space: [
      '-------------',
      '-----x-x-----',
      '----xxxxx----',
      '---xx-x-xx---',
      '----xoxox----',
      '---xxxxxxx---',
      '--x-x---x-x--',
      '-----x-x-----',
      '-------------',
    ],
    ghost: [
      '----------------',
      '------oooo------',
      '----oooooooo----',
      '---oooooooooo---',
      '--ooo--oooo--o--',
      '--oo----oo------',
      '--oo--88oo--88--',
      '-ooo--88oo--88o-',
      '-oooo--oooo--oo-',
      '-oooooooooooooo-',
      '-oooooooooooooo-',
      '-oooooooooooooo-',
      '-oooooooooooooo-',
      '-oo-ooo--ooo-oo-',
      '-o---oo--oo---o-',
      '----------------',
    ],
    deadhead: [
      '-------------',
      '--x-xxxxx-x--',
      '---xxxxxxx---',
      '---x0xxx0x---',
      '---xxxxxxx---',
      '---xxxxxxx---',
      '--x-xxxxx-x--',
      '-x---------x-',
      '-------------',
    ],
    myth: [
      '--x-------x--',
      '---x-----x---',
      '----x---x----',
      '---xxxxxxx---',
      '--xx-xxx-xx--',
      '-xxxxxxxxxxx-',
      '-x-xxxxxxx-x-',
      '-x-x-----x-x-',
      '----xx-xx----',
      '-----xxx-----',
    ],
    ship: [
      '------x------',
      '-----xxx-----',
      '-----xox-----',
      '----xx8xx----',
      '-xxxxxxxxxxx-',
      '--xx8xxx8xx--',
      '----o---o----'
    ],
  },
  types: {
    '-': 'empty',
    'x': 'plain',
    'o': 'light',
    '8': 'highlight',
  }
};
